/*
 * SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import React, { useCallback, useState } from 'react';

import styled from '@emotion/styled';
import { Button, Checkbox, Input, Row, Text } from '@zextras/carbonio-design-system';
import PropTypes from 'prop-types';
import { QRCodeSVG } from 'qrcode.react';
import { useTranslation } from 'react-i18next';

import { TwoFactorIntro, TwoFactorLogoHeader } from './two-factor-shared-header';
import { useLoginConfigStore } from '../store/login/store';

const SecretCodeBox = styled.div`
	width: 100%;
	padding: 16px;
	border: 1px solid #ccc;
	border-radius: 4px;
	text-align: center;
	word-break: break-all;
	font-size: 1.25rem;
	font-weight: bold;
	letter-spacing: 2px;
	font-family: Roboto, sans-serif;
`;

function extractSecretFromUri(uri) {
	try {
		const url = new URL(uri);
		return url.searchParams.get('secret') || '';
	} catch {
		return '';
	}
}

export default function OtpSetup({
	otpUri,
	onBackToLogin,
	onVerifyCode,
	disableInputs,
	loading,
	verifyError,
	attemptsRemaining,
	onBack
}) {
	const [t] = useTranslation();
	const { loginLogo } = useLoginConfigStore();
	const [code, setCode] = useState('');
	const [trustDevice, setTrustDevice] = useState(false);
	const toggleTrustDevice = useCallback(() => setTrustDevice((v) => !v), []);

	const hasError = !!verifyError;

	const secretCode = extractSecretFromUri(otpUri);

	const onChangeCode = useCallback((ev) => {
		const { value } = ev.target;
		setCode(value);
	}, []);

	const handleSubmit = useCallback(
		(e) => {
			e.preventDefault();
			if (code.length > 0) {
				onVerifyCode(code, trustDevice);
			}
		},
		[code, onVerifyCode, trustDevice]
	);

	return (
		<form onSubmit={handleSubmit} style={{ width: '100%' }}>
			<input type="submit" style={{ display: 'none' }} />
			<Row
				orientation="vertical"
				crossAlignment="flex-start"
				padding={{ bottom: 'small' }}
				width="100%"
			>
				<Button
					data-testid="back_to_login"
					type="ghost"
					onClick={onBackToLogin}
					label={t('back_to_login_page', 'Back to login page')}
					icon="ArrowBackOutline"
					iconPlacement="left"
				/>
			</Row>
			<TwoFactorLogoHeader loginLogo={loginLogo} />
			<TwoFactorIntro
				title={t(
					'otp_wizard_title',
					'Your organization introduced the Two-Factor-Authentication to improve the security of your account.'
				)}
				description={t(
					'otp_setup_description',
					'Configure the 2 Factor Authentication service (2FA) following few easy steps:'
				)}
			/>

			{/* Step 1 */}
			<Row padding={{ bottom: 'small', top: 'large' }} mainAlignment="flex-start">
				<Text weight="bold" overflow="break-word">
					{t('otp_setup_step1_title', 'Step 1')}
				</Text>
			</Row>
			<Row padding={{ bottom: 'large' }} mainAlignment="flex-start">
				<Text color="text" overflow="break-word">
					{t('otp_setup_step1_scan_qr', 'Use your authenticator app to scan the QR Code below')}
				</Text>
			</Row>

			{/* QR Code */}
			<Row padding={{ bottom: 'small' }} mainAlignment="flex-start">
				<div
					data-testid="otp_qr_code"
					style={{
						padding: '16px',
						border: '1px solid #ccc',
						borderRadius: '2px',
						display: 'inline-block'
					}}
				>
					<QRCodeSVG value={otpUri} size={140} />
				</div>
			</Row>

			<Row padding={{ top: 'large', bottom: 'small' }} mainAlignment="flex-start">
				<Text color="text" overflow="break-word">
					{t(
						'otp_setup_cant_scan',
						"Can't scan the code? Enter this secret code into your authenticator app"
					)}
				</Text>
			</Row>
			<Row padding={{ bottom: 'large' }} mainAlignment="flex-start">
				<SecretCodeBox data-testid="otp_secret_code">{secretCode}</SecretCodeBox>
			</Row>

			{/* Step 2 */}
			<Row padding={{ bottom: 'small', top: 'large' }} mainAlignment="flex-start">
				<Text weight="bold" overflow="break-word">
					{t('otp_setup_step2_title', 'Step 2')}
				</Text>
			</Row>
			<Row padding={{ bottom: 'small' }} mainAlignment="flex-start">
				<Text color="text" overflow="break-word">
					{t(
						'otp_setup_step2_enter_code',
						'Enter the 6-digit code generated by your authenticator app'
					)}
				</Text>
			</Row>
			<Row>
				<Input
					value={code}
					hasError={hasError}
					disabled={disableInputs}
					onChange={onChangeCode}
					label={t('otp_setup_code_placeholder', 'Insert the 6-digit code generated')}
					backgroundColor="gray5"
					data-testid="otp_setup_code_input"
				/>
			</Row>
			{hasError && (
				<Row padding={{ top: 'small' }} mainAlignment="flex-start">
					<Text color="error" size="small" overflow="break-word">
						{attemptsRemaining > 0
							? t(
									'otp_setup_code_error',
									'This code is incorrect or expired. Please try again. ({{count}} attempts remaining)',
									{ count: attemptsRemaining }
								)
							: t(
									'otp_setup_code_error_generic',
									'For your security, access has been restricted after too many incorrect attempts. Reload the page to start again the 2FA configuration flow'
								)}
					</Text>
				</Row>
			)}
			<Row padding={{ vertical: '40px' }} mainAlignment="flex-start">
				<Checkbox
					value={trustDevice}
					label={t('remember_device_or_ip', 'Remember this device or IP')}
					onClick={toggleTrustDevice}
				/>
			</Row>
			<Row mainAlignment="space-between" width="100%">
				<Row width="100%">
					<Button
						onClick={handleSubmit}
						disabled={disableInputs || code.length === 0}
						label={t('verify_and_proceed', 'Verify and proceed')}
						loading={loading}
						style={{ flex: 1 }}
						width="fill"
						data-testid="otp_setup_verify"
					/>
				</Row>
			</Row>
		</form>
	);
}
OtpSetup.propTypes = {
	otpUri: PropTypes.string.isRequired,
	onBackToLogin: PropTypes.func.isRequired,
	onVerifyCode: PropTypes.func.isRequired,
	disableInputs: PropTypes.bool,
	loading: PropTypes.bool,
	verifyError: PropTypes.string,
	attemptsRemaining: PropTypes.number,
	onBack: PropTypes.func.isRequired
};

OtpSetup.defaultProps = {
	disableInputs: false,
	loading: false,
	verifyError: undefined,
	attemptsRemaining: undefined
};
